[package]
name = "shdrs"
version = "0.1.0"
authors = ["Justin Shrake <justinshrake@gmail.com>"]

[dependencies]
glium = "*"
notify = "*"
time = "*"
clap = "*"
serde = "*" 
serde_json = "*" 
serde_macros = "*"
