[package]
name = "shdrs"
version = "0.1.0"
authors = ["Justin Shrake <justinshrake@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[dependencies]
glium = "*"
notify = "*"
time = "*"
clap = "*"
serde = "*" 
serde_json = "*" 

